[dev]
    command = 'npm run dev'
    publish = '_site'

[build]
    command = 'sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev && npm run build'
    publish = '_site'
